<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ecom_config_code_generator"
 *
 * Auto generated by Extension Builder 2015-09-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Config code generator',
	'description' => 'Configuration code generator',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'Sebastian.Iffland@ecom-ex.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.2.0',
	'constraints' => [
		'depends' => [
			'cms' => '',
			'typo3' => '6.2',
			'php' => '5.5',
			'ecom_toolbox' => '1.2.0',
			'powermail' => ''
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];